Update conditional-test.yml

diff --git a/.github/workflows/conditional-test.yml b/.github/workflows/conditional-test.yml
--- a/.github/workflows/conditional-test.yml
+++ b/.github/workflows/conditional-test.yml
@@ -8,7 +8,9 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Step 1
-        run: echo "This step will fail" && exit 1
+        run: |
+          echo "This step will fail"
+          exit 1
       - name: Step 2
         run: echo "Continued after failure"
   after-test:
